### ISSUE TITLE
Issue when running patch.sh

### ISSUE THREAD

**Issue by abe-q** [RiiConnect24/IOS-Patcher#11] opened 2017-06-18 23:46 UTC
When I run patch.sh on a mac, it spits out this error:
`1. Downloading IOS from NUS... 
Cannot open assembly 'Sharpii.exe': No such file or directory.
Cannot open assembly 'Sharpii.exe': No such file or directory.
2. Unpacking IOS... 
cp: IOS31-old/000000010000001fv3608.wad: No such file or directory
cp: IOS80-old/0000000100000050v6944.wad: No such file or directory
Cannot open assembly 'Sharpii.exe': No such file or directory.
Cannot open assembly 'Sharpii.exe': No such file or directory.
3. Patching the APP file... 
/Users/abequinn/Downloads/Mac/patch.sh: line 14: ./xdelta3: No such file or directory
/Users/abequinn/Downloads/Mac/patch.sh: line 15: ./xdelta3: No such file or directory
4. Packing the new IOS... 
mkdir: WAD: File exists
Cannot open assembly 'Sharpii.exe': No such file or directory.
Cannot open assembly 'Sharpii.exe': No such file or directory.
5. Cleaning up files... (Type Y if needed). 
rm: IOS31-old.wad: No such file or directory
rm: IOS80-old.wad: No such file or directory
We're done.
`

**Comment by abe-q** [comment] 2017-06-18 23:48
Fixed it, thanks.

**Comment by spotlightishere** [comment] 2017-06-18 23:56
Did you figure out what the issue is? I'd love to fix it so others don't have the issue.

**Comment by KcrPL** [comment] 2017-06-19 05:16
He probably didn't downloaded entire directory, only patch.sh

**Comment by spotlightishere** [comment] 2017-06-19 05:19
My fault for not updating the issue. 

In Bash (so .sh, etc), everything is relative to the current directory, unlike .desktop files in Linux or .command files on macOS. They went to the terminal and ran `bash ~/Downloads/IOS-Patcher/Mac/patch.sh`, whereas their current directory was elsewhere (I'm assuming the home directory). Hence, it was looking for `~/xdelta3` instead of `~/Downloads/IOS-Patcher/Mac/xdelta3`.

I'll be updating the patcher tomorrow to support this cause, by adding a command file (so the Terminal can handle it, quite literally relatively) and updating the bash script to cd itself to the directory it's contained in.

**Comment by KcrPL** [comment] 2017-06-19 05:52
Maybe your patcher should be checking for files like mine does?

**Comment by abe-q** [comment] 2017-06-19 14:42
To fix it,  I cd'd to the download (Mac) and ran it again.
(thanks guys)

**Comment by spotlightishere** [comment] 2017-06-19 15:51
All that’s needed to be done is to have the script cd where it’s from. File checking won’t be needed, nor would help.

**Comment by KcrPL** [comment] 2017-06-20 16:00
Spot,
I think your patcher should be checking for files like xdelta etc.
You know, there are some people's that download only patch.sh - not entire directory.

I'm closing that issue... for now. I think it has been fixed ;)

**Comment by abe-q** [comment] 2017-06-20 16:02
Somebody on discord had the same issue, by the way.

**Comment by spotlightishere** [comment] 2017-06-20 16:03
I fixed it for the Linux version, have yet to for macOS.

**Comment by abe-q** [comment] 2017-06-20 16:08
Did you add the linux one to macOS?
http://prntscr.com/fm20jw

**Comment by spotlightishere** [comment] 2017-06-20 16:11
I went ahead and added a one-liner for it to `cd` to the directory it's running, and since it works on macOS I copied that there too. I'm about to push a commit which'll `chmod a+x` the `patch.sh`(s) and a new run.command (which one can open in Terminal to run).

**Closed as completed** 2017-06-20 16:14 UTC
Labels: bug, fixed, UNIX
