### ISSUE TITLE
An exception occurred during a WebClient request

### ISSUE THREAD

**Issue by GtgGhost** [RiiConnect24/IOS-Patcher#21] opened 2017-10-23 15:38 UTC
Windows 10 Home Version 1709

> The system cannot find the path specified.
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request.

At line:1 char:1
+ (new-object System.Net.WebClient).DownloadFile('https://kcrpl.github. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:1 char:1
+ (new-object System.Net.WebClient).DownloadFile('https://kcrpl.github. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

The system cannot find the path specified.
set was unexpected at this time.

**Comment by GtgGhost** [comment] 2017-10-23 15:52
I think it's this bit - (set FilesHostedOn=https://kcrpl.github.io/Patchers_Auto_Update/IOS_Patcher)

when going to that address I get

> 404

> File not found

> The site configured at this address does not contain the requested file.

> If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

> Read the full documentation for more information about using GitHub Pages.

> GitHub Status — @githubstatus"

**Comment by KcrPL** [comment] 2017-10-23 15:53
No, this variable is ok. Thank you for making this issue. I'm gonna work on it later.

**Comment by KcrPL** [comment] 2017-10-23 15:57
After that powershell error, does it crash?

**Comment by GtgGhost** [comment] 2017-10-23 15:59
yes unless i run it from cd

**Comment by KcrPL** [comment] 2017-10-23 16:00
cd? What do you mean?

**Comment by GtgGhost** [comment] 2017-10-23 16:01
doesn't crash just closes

**Comment by KcrPL** [comment] 2017-10-23 16:03
The powershell part is not really a problem, some computers have problem with autoupdating. `The system cannot find the path specified.
set was unexpected at this time` is the problem. I will work on it later.

**Comment by GtgGhost** [comment] 2017-10-23 16:12
I don't have a folder in my \AppData\Roaming named (IOSPatcher)

maybe that helps?

**Comment by KcrPL** [comment] 2017-10-23 16:13
I dunno, i'll see what I can do.

**Comment by GtgGhost** [comment] 2017-10-23 16:16
I don't mean to come off like i'm rushing you. Take your time I really don't know anything about this stuff it's probably on my end...

**Comment by KcrPL** [comment] 2017-10-23 17:26
Actually a lot of people reported this. I'm gonna work on it now. @GtgGhost

**Comment by KcrPL** [comment] 2017-10-23 17:37
After some testing, i cannot reproduce the problem. Only thing that I can do is adding some kind of a failsafe that will enter the debug menu after some problems. I'm gonna close this problem for now.

Thanks for submiting this.

**Closed as completed by KcrPL** 2017-10-23 17:37 UTC
Labels: bug, fixed, Windows

**Comment by KcrPL** [comment] 2017-10-31 00:56
@GtgGhost: This issue has been fixed. Download it from [here](https://github.com/RiiConnect24/IOS-Patcher/releases)

**Comment by KcrPL** [comment] 2018-01-14 10:02
I would like to notice you that this error has been fixed 100%.
